export default {
  GET_TRENDING_MOVIES: 'GET_TRENDING_MOVIES',
  GET_TOP_RATED_MOVIES: 'GET_TOP_RATED_MOVIES',
  GET_TOP_RATED_TV: 'GET_TOP_RATED_TV',
  GET_MOVIE_DETAILS: 'GET_MOVIE_DETAILS',
  GET_SEARCH_RESULTS: 'GET_SEARCH_RESULTS',
  GET_MOVIE_GENRES: 'GET_MOVIE_GENRES',
  GET_SERIES_GENRES: 'GET_SERIES_GENRES',
  GET_POPULAR_PEOPLE: 'GET_POPULAR_PEOPLE',
  GET_FILTERED_MOVIES: 'GET_FILTERED_MOVIES',
  GET_FILTERED_PEOPLE: 'GET_FILTERED_PEOPLE',
  GET_FILTERED_SERIES: 'GET_FILTERED_SERIES',
  SUBMIT_RATING: 'SUBMIT_RATING',
};